# Generated by Django 2.2 on 2019-04-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0003_auto_20190423_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='user',
        ),
    ]
