# Generated by Django 2.2 on 2019-04-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0004_remove_blog2_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='usr_id',
        ),
    ]
